GET localhost:7070/api/routes

###
GET localhost:7070/api/skilesson

###
GET localhost:7070/api/skilesson/12

###
POST localhost:7070/api/skilesson
Content-Type: application/json

{
  "startTime": "09:00",
  "endTime": "12:00",
  "startPosition": "47.3455, 12.7965",
  "name": "Beginner Avalanche Survival",
  "price": 45.50,
  "level": "BEGINNER"
}

###
PUT localhost:7070/api/skilesson/13/instructor/1


###
PATCH localhost:7070/api/skilesson/13
Content-Type: application/json

{
  "startTime": "13:00",
  "endTime": "16:00"
}

###
GET localhost:7070/api/skilesson/level?level=BEGINNER

###
GET localhost:7070/api/skilesson/instructor/1/overview

###
GET localhost:7070/api/skilesson/stats

###
DELETE localhost:7070/api/skilesson/13

###
POST localhost:7070/api/skilesson/populate